module.exports = {
  presets: ['@vue/cli-plugin-babel/preset'],
  plugins: [
    [
      'prismjs',
      {
        languages: [
          'bash',
          'c',
          'cmake',
          'cpp',
          'crystal',
          'd',
          'diff',
          'docker',
          'glsl',
          'go',
          'graphql',
          'handlebars',
          'haskell',
          'html',
          'javascript',
          'json',
          'jsx',
          'lisp',
          'lua',
          'makefile',
          'markdown',
          'nim',
          'powershell',
          'python',
          'racket',
          'regex',
          'ruby',
          'rust',
          'scheme',
          'sql',
          'tsx',
          'typescript',
          'yaml',
          'zig',
        ],
        plugins: ['line-numbers'],
        theme: 'tomorrow',
        css: true,
      },
    ],
  ],
};
